apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-example
  labels:
    app: cicd-example
spec:
  replicas: 2 # pod count
  selector:
    matchLabels:
      app: cicd-example
  template:
    metadata:
      name: cicd-example
      labels:
        app: cicd-example
    spec:
      containers:
        - name: cicd-example
          image: local/cicd-example:latest # Image that will be used inside the container in the cluster
          imagePullPolicy: Never #IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
 name: cicd-example
 labels:
  app: cicd-example
spec:
  type: NodePort
  selector:
    app: cicd-example
  ports:
    - name: http
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080
