name: CI Pipeline (DOC1)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: My First Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: To Show Error (This will fail)
        run: |
          echo "Should fail at this point ..."
          exit 1
      
      - name: Run a one-line script
        run: echo "Continuous Integration"
